### ISSUE TITLE
Removing useless ore dictionary entries.

### ISSUE THREAD

**Issue by Claycorp** [Xexanos/PoorOres#10]
Nuggets and ores are all oreditconared under the same thing meaning they are equal... They definitely are not equal.

Because of this you can take a lesser item and "transmute" it into something else because of unifying.
Jabba barrels and the Drawers mod both do this.

**Comment by Xexanos** [comment]
good point, I added them to make it possible to add recipes saying "just use a random nugget" but I don't think, that this will make sense with unifying.
