### ISSUE TITLE
Breaking some ores should drop nuggets not ores.

### ISSUE THREAD

**Issue by Claycorp** [Xexanos/PoorOres#5]
Diamond, Emerald, Coal... Any other gem or ores that drop items.

This is especially the case with coal as getting the coal out of the ore is less efficient than making charcoal or using planks thus making the ores completely pointless unless you need the coal for a crafting recipe.

Adding in a new line to the config for this option would be optimal.
I:blockDropsNuggets=0/1 or S:blockDropsNuggets:true/false

**Comment by Xexanos** [comment]
I did it a little different and just take a look at the original ore. If that drops an item I also drop an item... and I adjusted the amount dropped, to accommodate, that for example lapis does not only drop one but multiple items at a time.

Ps.: thanks for fixing my code for the other bugs btw. I don't know, how long I would have been searching for that error :)

**Comment by Claycorp** [comment]
Hey not a problem! I glad my extremely limited knowledge could be of use :P

I would have never known of the issue if it wasn't for me trying to make Dence ores spawn with poor ores. I Still don't think it works but i have no idea why as getting into that stuff is complicated...
