### ISSUE TITLE
Can't make new ores.

### ISSUE THREAD

**Issue by Claycorp** [Xexanos/PoorOres#7]
My version (UNOFFICIAL V4) works fine. The new build you have 1.4.1 does not generate any custom ores. Vanilla seems to works fine.

I will be trying each new build you made to see if its pinpointable.

**Comment by Claycorp** [comment]
1.3.2 does not work with custom ores. 
All i can find is:
[19:04:11] [Client thread/WARN] [PoorOres]: copper: Baseblock "TConstruct:SearedBrick" not found.
[19:04:11] [Client thread/WARN] [PoorOres]: copper: Ore will not be added.

This doesn't make sense as the same config works with my update... Its also an updated config.

**Comment by Xexanos** [comment]
The problem seems to be, that the mod the ore originally comes from is not loaded yet or at least hasn't registered any ore yet. I'm currently trying to find a way around that.

**Comment by Claycorp** [comment]
That doesn't make sense at all.. as thats what the fix i did was for. 
You did something different between my patch and what you updated that broke it again.

What that is i have no clue.

**Comment by Xexanos** [comment]
I found a workaround to fix the problem. Essentially I disregard the security check to find the right baseblock in preInit and instead try to find it later, when it is needed.

**Comment by Xexanos** [comment]
I think the reason your version did not have that problem was simply because the mods are loaded in alphabetical order (I think). So unless I find a way to tell forge to try loading my mod after all other mods that add some kind of ore this problem can only be solved by hoping the way I worked around it will not explode in my face^^

**Comment by Claycorp** [comment]
Well if you use other ores you can move that stuff to init. At the time of me editing it i really did not know much about the mod and it still worked at preinit when i was messing with it...

Also it was the same mod i was editing. Tinkers copper. Worked in my version and your version did not. I doubt an update would change the load order like that.

We all are learning something here! :+1:
