### ISSUE TITLE
[Suggestion] Tiny Pile of Dusts

### ISSUE THREAD

**Issue by AegisLesha** [Xexanos/PoorOres#9]
Well this is pretty simple: Redstone Nuggets are kind of silly, shouldn't you add a texture for, and some lines of code to switch some poor ores from giving nuggets to tiny piles, like vanilla Redstone, BluePower Teslatite or HarvestCraft Salt, for instance?

**Comment by Xexanos** [comment]
sounds like a good Idea. I will look into adding an option in the config to change the name and the appearance to tiny piles. The only problem this might cause is, that, whenn you are playing with gregtech installed it adds recipes for 4 tiny piles to make one normal pile (at least for the metals). this could lead to a conflict.
